#!/bin/bash

# Logging
log_message() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" >&2
}

# Link entfernen
log_message "Entferne symbolischen Link..."
rm -f /usr/bin/gpu-cpu

log_message "Deinstallation abgeschlossen."

